Update functions_abstract.py
Update to python3 lib

  File "/opt/stat/system/plugins/TracSlackExtend-0.1.0-py3.6.egg/trac_slack_extend/common/functions_abstract.py", line 1, in <module>
    from urlparse import urlparse
ModuleNotFoundError: No module named 'urlparse'